apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-serving
spec:
  selector:
    app.kubernetes.io/name: serving
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 8000
      targetPort: 8000
