FROM vllm/vllm-openai:v0.27.1

ENTRYPOINT ["vllm", "serve"]

CMD ["Qwen/Qwen3-8B-AWQ", \
     "--host", "0.0.0.0", \
     "--port", "8000", \
     "--max-model-len", "4096", \
     "--gpu-memory-utilization", "0.30"]
