FROM vllm/vllm-openai:v0.27.1

CMD ["humain-ai/ALLaM-7B-Instruct-preview", \
     "--host", "0.0.0.0", \
     "--port", "8000", \
     "--dtype", "half", \
     "--max-model-len", "4096", \
     "--gpu-memory-utilization", "0.85"]
