FROM vllm/vllm-openai:v0.27.1

ENTRYPOINT ["vllm", "serve"]

CMD ["jeffcookio/Mistral-Small-3.2-24B-Instruct-2506-awq-sym", \
     "--host", "0.0.0.0", \
     "--port", "8000", \
     "--max-model-len", "4096", \
     "--gpu-memory-utilization", "0.32"]
